ARG TAG=18-alpine

FROM node:$TAG as typescript-dev

ARG PORT=80

WORKDIR /app

COPY . .

RUN npm install --package-lock --save-exact --strict-peer-deps --audit --ignore-scripts &&\
  npm cache clean --force

EXPOSE $PORT

CMD ["npm", "run", "dev"]
